version: "3"
services:
  node-app-nginx:
    image: nginx:stable-alpine
    container_name: node-app-nginx-container
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    image: node-app-image:1.0
    # container_name: node-app-container
    environment:
      - PORT=3000
    depends_on:
      - node-app-db

  node-app-db:
    image: mongo
    container_name: node-app-db-container
    volumes:
      - mongo-db_data:/data/db

  node-app-redis:
    image: redis
    container_name: node-app-redis-container

volumes:
  mongo-db_data:
