version: "3"
services:
  node-app-nginx:
    ports:
      - "3000:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
    environment:
      - NODE_ENV=development
      - MONGO_USER=bishant
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev

  node-app-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bishant
      - MONGO_INITDB_ROOT_PASSWORD=password
